print('Kali Linux')
print('')
print('Login: root')
print('Password: toor')
print('')
print('1) Aircrack-NG')
print('2) JohnTheRipper')
print('3) NMAP')
print('4) Thunderbird')
print('5) Terminal')
print('6) Wireshark')
print('7) Python')
print('8) Burp Suite')
print('9) Shodan')
print('10) Tor')
print('11) Orbot')
print('12) Metasploit')
print('13) Hydra')
print('14) Nikto')
print('15) skipfish')
print('16) GHunt')
print('17) Trape')
print('18) TBomb')
print('19) checkIP')
print('20) VeraCrypt')
print('21) Keyword tool')
print('22) Device Profiler')
print('23) Wine')
print('24) Google Dork')
print('25) AhMyth')
print('26) usbrip')
print('27) Malware')
print('28) cameradar')
utsel = input('Select Utility: ')
if utsel == ('1'):
    print('Aircrack-NG')
    print('')
    print('1) TP Link')
    print('2) Rt WiFi')
    wifisel = input('Select Wi-Fi: ')
    print('')
    aireplay = input('$ ')
    if aireplay == ('aireplay'):
        print('Find 7063 passwords')
        aircrack = input('$ ')
        if aircrack == ('aircrack'):
            print('Password: admin')
            print('Done')
if utsel == ('2'):
    print('JohnTheRipper')
    print('')
    print('1) games.rar')
    print('2) SCP.rar')
    print('3) films.rar')
    arcgivsel = input('Select archive: ')
    print('Password: archive')
    print('Done')
if utsel == ('3'):
    print('NMAP')
    print('')
    print('IP: 192.168.0.1')
    print('')
    print('1) 4pda.ru')
    print('2) scanme.nmap.org')
    print('3) godville.net')
    sitenmapsel = input('Select URL: ')
    scancmd = input('$ ')
    if scancmd == ('nmap -v'):
        print('URL scan...')
        print('port 1400 open')
        print('port 4924 open')
        print('port 8486 close')
        print('Done')
if utsel == ('4'):
    print('Thunderbird')
    print('')
    youemail = input('You email: ')
    toemail = input('Send to: ')
    txtemail = input('Text: ')
    print('Done')
if utsel == ('5'):
    print('Terminal')
    print('')
    termcmdrand = input('$ ')
    if termcmdrand == ('ip'):
        print('IP: 192.168.0.1')
    if termcmdrand == ('whoami'):
        print('root@admin')
    if termcmdrand == ('kill'):
        print('')
    if termcmdrand == ('dir'):
        print('utilties.py')
if utsel == ('6'):
    print('Wireshark')
    print('')
    print('1) localhost:1')
    print('2) 192.168.0.1')
    print('3) 124.234.6.3')
    wirescansel = input('Select target: ')
    print('')
    print('1) photos')
    print('2) passwords')
    infosel = input('Select info: ')
    if infosel == ('1'):
        print('Photos')
        print('')
        print('Photos no find')
    if infosel == ('2'):
        print('Passwords')
        print('')
        print('RT-Wi-Fi password: admin')
if utsel == ('7'):
    print('Python')
    print('')
    pytcmdrand = input('>> ')
if utsel == ('8'):
    print('Burp Suite')
    print('')
    print('1) Proxy')
    print('2) Reporter')
    print('3) Intuder')
    print('4) Extender')
    burputsel = input('Utilty: ')
    if burputsel == ('1'):
        print('Proxy')
        print('')
        burpurl = input('URL: ')
        print('Attack done')
    if burputsel == ('2'):
        print('Reporter')
        print('')
        print('No')
    if burputsel == ('3'):
        print('Intuder')
        print('')
        burphost = input('Host: ')
        burpport = input('Port: ')
        print('Attack done')
    if burputsel == ('4'):
        print('Extennder')
        print('')
        print('No')
if utsel == ('9'):
    print('Shodan')
    print('')
    print('1) Site scan')
    print('2) IP Camera')
    shoutsel = input('Select utilty: ')
    if shoutsel == ('1'):
        print('Site scan')
        print('')
        shogeturl = input('URL: ')
        print('Scan done')
        print('HTTPS')
        print('content-type: text/html')
        print('Link: <' + shogeturl + '>')
    if shoutsel == ('2'):
        print('IP Camera')
        print('')
        shoipcam = input('Camera IP: ')
        print('Camera not find')   
if utsel == ('10'):
    print('Tor')
    print('')
    print('1) Drug')
    print('2) Weapon')
    darknetsitesel = input('Go to: ')
    if darknetsitesel == ('1'):
        print('Drugs')
        print('')
        print('Site is blocked')
    if darknetsitesel == ('2'):
        print('Weapon')
        print('')
        print('Site is blocked')
if utsel == ('11'):
    print('Orbot')
    print('')
    print('VPN')
    print('1) England')
    print('2) America')
    print('3) Africa')
    print('4) Kanada')
    print('5) Argentina')
    vpnlocsel = input('Select location: ')
    print('Done')
if utsel == ('12'):
    print('Metasploit')
    print('')
    print('$ msfconsole')
    print('metasploit v5.0.56-dev')
    print('')
    msfconsole = input('msf5 > ')
    if msfconsole == ('db_status'):
        print('[*] Connected')
    if msfconsole == ('portscan'):
        print('Ports')
        print('')
        print('[+] 192.168.0.1: CP OPEN')
        print('[+] 192.168.0.1: TCP OPEN')
if utsel == ('13'):
    print('Hydra')
    print('')
    print('Scanning...')
    print('1) Arch Linux')
    print('2) Debian')
    print('3) Kubuntu')
    print('4) Ubuntu')
    hydraattacksel = input('Select target: ')
    print('root/toor')
    print('Done')
if utsel == ('14'):
    print('Nikto')
    print('')
    niktourl = input('Enter URL: ')
    print('')
    print('Find:')
    print('index.html')
    print('icon.ico')
    print('ads.js')
    print('')
    print('Done')
if utsel == ('15'):
    print('skipfish')
    print('')
    skipfishurl = input('Enter URL: ')
    print('')
    print('Crawl resilts')
    print('New 404 signature seen')
    print("New 'Server' header value seen")
    print('+ .svn')
    print('cgi-bin')
    print('- error')
    print(' .svn')
    print(' + include')
    print(' + README')
    print('+ icons')
    print('index.html')
if utsel == ('16'):
    print('GHunt')
    print('')
    ghuntmail = input('Enter GMail: ')
    print('YouTube channel: no')
    print('Googe ADMob: no')
    print('Google ADSence: no')
    print('Google ID: XXX')
    print('Auth in: GChrome, GPlay, GPhoto, YouTube')
if utsel == ('17'):
    print('Trape')
    print('')
    trapeport = input('Port: ')
    trapeurl = input('Fishing URL: ')
    print('Done')
if utsel == ('18'):
    print('TBomb')
    print('')
    tbombnum = input('Number Phone: ')
    tbombtxt = input('Spam text: ')
if utsel == ('19'):
    print('checkIP')
    print('')
    print('You IP: 192.168.0.1')
if utsel == ('20'):
    print('VeraCrypt')
    print('')
    zuluzip = input('Enter Archive: ')
    zulupass = input('Enter password: ')
    print('Done')
if utsel == ('21'):
    print('Keyword tool')
    print('')
    keywordsearch = input('Search: ')
    print('Google: yes')
    print('YouTube: no')
    print('Twitter: no')
    print('Instagram: no')
    print('Amazon: no')
    print('eBay: no')
    print('Play Store: no')
    print('Bing: yes')
if utsel == ('22'):
    print('Device Profiler')
    print('')
    print('Samsung S10')
    print('Acer Nitro 5')
    print('Xiaomi Redmi 6A')
    print('Huawei Y5 2019')
    print('Honor 8A')
    print('Umidigi A3')
    print('Honor 7A')
    print('Xiaomi Pocophone F1')
    print('Samsung Galaxy Tab A')
    print('Prestigio Grace 4G')
    print('Umi Rome X')
if utsel == ('23'):
    print('Wine')
    print('')
    print('Fatal error')
if utsel == ('24'):
    print('Google Dork')
    print('')
    googledorksite = input('$ inurl: ')
    print('Scan filed')
if utsel == ('25'):
    print('AhMyth')
    print('')
    print('APK Building')
    print('(print "build" to build APK)')
    ahmythbuildapk = input('$ ')
    if ahmythbuildapk == ('build'):
        print('')
        print('APK is building')
if utsel == ('26'):
    print('usbrip')
    print('')
    print('         _       _')
    print(' _ _ ___| |_ ___|.|___')
    print('| | |  _|   |  _| | . |')
    print('|   |_  | . | | | |  _|')
    print('|___|___|___|_| |_|_|')
    print('')
    usbripcmdrand = input('>> python3 usbrip.py ')
    if usbripcmdrand == ('-h'):
        print('Modules not find')
    if usbripcmdrand == ('banner'):
        print('         _       _')
        print(' _ _ ___| |_ ___|.|___')
        print('| | |  _|   |  _| | . |')
        print('|   |_  | . | | | |  _|')
        print('|___|___|___|_| |_|_|')
if utsel == ('27'):
    print('Malware')
    print('')
    malwarevirus = input('What virus: ')
    malwarerar = input('Archive name: ')
    print('Archive "' + malwarerar + '" with virus "' + malwarevirus + '"')
    print('Done')
if utsel == ('28'):
    print('cameradar')
    print('')
    cameradarip = input('cameradar -t ')
    print('Camera not find')