print('Mind Mapping')
print('')
print('')
q = input('1) ')
q1 = input('1.1) ')
q2 = input('1.2) ')
print('')
w = input('2) ')
w1 = input('2.1) ')
w2 = input('2.2) ')
print('')
e = input('3) ')
e1 = input('3.1) ')
e2 = input('3.2) ')
print('')
r = input('4) ')
r1 = input('4.1) ')
r2 = input('4.2) ')
print('')
print('')
print('1) ' + str(q) + ', ' + str(q1) + ', ' + str(q2))
print('2) ' + str(w) + ', ' + str(w1) + ', ' + str(w2))
print('3) ' + str(e) + ', ' + str(e1) + ', ' + str(e2))
print('4) ' + str(r) + ', ' + str(r1) + ', ' + str(r2))
ext = input('')
