sutrait = ('100')
arenarait = ('1400')
print('V DAMKI')
print('')
money = ('100')
print('Деньги: ' + str(money) + '$')
stalkcount = ('10')
print('Сталкеры: ' + str(stalkcount))
print('')
print('1) Главное здание')
print('2) Магазин')
print('3) Ученые')
print('4) Арена')
print('5) Бар')
gotosel = input('Войти в: ')
if gotosel == ('1'):
    print('Главное здание')
    print('')
    print('1) Рейд')
    print('2) Сталкеры')
    print('3) Сейф')
    print('4) Мастерская')
    print('5) Статистика')
    print('6) Нападение')
    print('7) Гарнизон')
    print('8) Склад')
    print('9) Кланы')
    print('10) Защита')
    maingotosel = input('Пойти в: ')
    if maingotosel == ('1'):
        print('Рейд')
        print('')
        print('1) Кордон')
        print('2) Южное болото')
        print('3) Деревня')
        print('4) Ближний лес')
        print('5) Желтое озеро')
        mainraidsel = input('Пойти в: ')
        print('Рейд прошел успешно')
    if maingotosel == ('2'):
        print('Сталкеры')
        print('')
        print('stlk_1')
        print('stlk_2')
        print('stlk_3')
        print('stlk_4')
        print('stlk_5')
        print('stlk_6')
        print('stlk_7')
        print('stlk_8')
        print('stlk_9')
        print('stlk_10')
    if maingotosel == ('3'):
        print('Сейф')
        print('')
        mainsafein = input('Сколько денег положить в сейф: ')
        print('Готово')
    if maingotosel == ('4'):
        print('Мастерская')
        print('')
        print('1) Улучшение')
        print('2) Закалка')
        mainmassel = input('Что сделать: ')
        if mainmassel == ('1'):
            print('Улучшение')
            print('')
            print('1) АК-47')
            print('2) Макаров')
            mainmasupsel = input('Что улучшить: ')
            print('Готово')
        if mainmassel == ('2'):
            print('Заклка')
            print('')
            print('1) АК-47')
            print('2) Макаров')
            mainmaszasel = input('Что закалить: ')
            print('Готово')
    if maingotosel == ('5'):
        print('Статистика')
        print('')
        print('Рейтинг нападений за сутки: ' + str(sutrait))
        print('Рейтинг арены: ' + str(arenarait))
    if maingotosel == ('6'):
        print('Нападение')
        print('')
        print('1) Разведка')
        print('2) Нападение')
        mainnapsel = input('Выберите действие: ')
        if mainnapsel == ('1'):
            print('Разведка')
            print('')
            print('Разведка прошла успешно')
        if mainnapsel == ('2'):
            print('Нападение')
            print('')
            print('Нападение прошло успешно')
    if maingotosel == ('7'):
        print('Гарнизон')
        print('')
        print('Гарнизон пуст')
    if maingotosel == ('8'):
        print('Склад')
        print('')
        print('1) АК-47')
        print('2) Макаров')
    if maingotosel == ('9'):
        print('Кланы')
        print('')
        print('1) Нас Рать')
        print('2) Монолит')
        print('3) Д.О.Л.Г')
    if maingotosel == ('10'):
        print('Защита')
        print('')
        print('Пвп-режим: отключен')
if gotosel == ('2'):
    print('Магазин')
    print('')
    print('1) Продать предметы')
    print('2) Купить предметы')
    print('3) Продать на ярмарке')
    print('4) Купить на ярмарке')
    magsel = input('Выберите вид: ')
    if magsel == ('1'):
        print('Продать предметы')
        print('')
        print('1) АК-47')
        print('2) Макаров')
        prodmag = input('Продать: ')
        print('Готово')
    if magsel == ('2'):
        print('Купить предметы')
        print('')
        print('1) Аптечка')
        print('2) Детектор')
        print('3) Костюм сталкера')
        buymag = input('Купить: ')
        print('Готово')
    if magsel == ('3'):
        print('Продать на ярмарке')
        print('')
        print('1) АК-47')
        print('2) Макаров')
        prodyar = input('Продать: ')
        print('Готово')
    if magsel == ('4'):
        print('Купить на ярмарке')
        print('')
        print('1) Военный костюм')
        print('2) Костюм наемника')
        print('3) Обрез')
        buyyar = input('Купить: ')
        print('Готово')
if gotosel == ('3'):
    print('Ученые')
    print('')
    print('1) Продать предметы')
    print('2) Купить предметы')
    uchdosel = input('Выберите действие: ')
    if uchdosel == ('1'):
        print('Продать предметы')
        print('')
        print('У вас нет артефактов')
    if uchdosel == ('2'):
        print('Купить предметы')
        print('')
        print('1) Аптечка')
        print('2) Костюм ученого')
        print('3) Детектор')
        uchbuy = input('Купить: ')
        print('Готово')
if gotosel == ('4'):
    print('Арена')
    print('Ваш рейтинг: ' + str(arenarait))
    print('')
    print('1) Выставить бойца')
    print('2) Мои бои')
    print('3) Сделать ставку')
    print('4) Мои ставки')
    print('5) Таблица лидеров')
    ardo = input('Выберите действие: ')
    if ardo == ('1'):
        print('Выставить бойца')
        print('')
        print('У вас нет свободных бойцов')
    if ardo == ('2'):
        print('Мои бои')
        print('')
        print('Вы еще не проводили боев')
    if ardo == ('3'):
        print('Сделать ставку')
        print('')
        print('1) Сталкер')
        print('2) Бандит')
        arstav = input('Выберите бойца: ')
        if arstav == ('1'):
            print('Вы победили')
        if arstav == ('2'):
            print('Вы проиграли')
    if ardo == ('4'):
        print('Мои ставки')
        print('')
        print('Вы еще не делали ставок')
    if ardo == ('5'):
        print('Таблица лидеров')
        print('')
        print('1) KVAZAR')
        print('2) ХЕМУЛЬ')
        print('3) Tsifra')
if gotosel == ('5'):
    print('Бар')
    print('')
    print('1) Да')
    print('2) Нет')
    barstalk = input('Нанять сталкера?: ')
    if barstalk == ('1'):
        print('Сталкер нанят')
    if barstalk == ('2'):
        print('Вы отменили наем сталкера')
